spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/black_postoffice?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: debug
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"