server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/black_postOffice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
