spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/black_postoffice?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: blackpostoffice-profile
    region:
      static: ap-northeast-2
    base:
      url : "https://blackpostoffice-profile.s3.ap-northeast-2.amazonaws.com/"
    stack:
      auto : false


logging:
  level:
    root: debug
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"